config/routes.rb
Rails.application.routes.draw do
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :player
  belongs_to :game

  after_create :handle_payments

  def handle_payments
    paying_odds = { green: 15, red: 2, black: 2 }
    factor = choice == game.result ? paying_odds[choice.to_sym] : 0
    update_player_wallet(factor)
  end

  def update_player_wallet(factor)
    player.update(wallet: player.wallet + amount * (factor - 1))
  end

  enum choice: %i[green red black]
end

app/models/game.rb
class Game < ApplicationRecord
  include Picker
  before_save :set_result
  after_create :new_round
  has_many :bets
  has_many :players, through: :bets

  def set_result
    self.result = pick_one
  end

  def new_round
    Player.place_bets(self)
  end

  enum result: %i[green red black]
end

app/models/player.rb
class Player < ApplicationRecord
  include Picker

  has_many :bets
  has_many :games, through: :bets
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :wallet, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.place_bets(game)
    all.each do |player|
      next if player.wallet.zero?

      Bet.create(
        player: player,
        game: game,
        amount: player.bet_amount,
        choice: player.pick_one
      )
    end
  end

  def bet_amount
    wallet <= 1000 ? wallet : (wallet * rand(bet_range)).to_i
  end

  def bet_range
    0.08..0.15
  end

  def self.daily_bonus(bonus_amount = 10_000)
    all.each { |player| player.update(wallet: player.wallet + bonus_amount) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[edit update destroy]

  def index
    @players = Player.order(:created_at)
  end

  def new
    @player = Player.new
    respond_to :js
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      respond_to :js
    else
      redirect_to players_path, alert: 'Please try again.'
    end
  end

  def edit
    respond_to :js
  end

  def update
    if @player.update(player_params)
      respond_to :js
    else
      redirect_to players_path, alert: 'Please try again.'
    end
  end

  def destroy
    @player.destroy
    respond_to :js
  end

  private

  def player_params
    params.require(:player).permit(:name, :email, :wallet)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherRoulette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/players/_player.html.erb
<div id="<%= player.id %>" class="row">
  <div class="col-3"><%= player.name %></div>
  <div class="col-3"><%= player.email %></div>
  <div class="col-3"><%= player.wallet %></div>
  <div class="col-3">
    <%= link_to "Edit", edit_player_path(player), class: 'btn btn-info btn-sm editPlayer', data: { remote: true } %>
    <%= link_to "Remove", player_path(player), class: 'btn btn-danger btn-sm', data: { remote: true, method: :delete } %>  
  </div>
</div>

app/views/players/create.js.erb
$('#newPlayerForm').replaceWith('<%= j render @player %>');
$('#newPlayer').removeClass('disabled');

app/views/players/destroy.js.erb
$('#<%= @player.id %>').hide(300);

app/views/players/edit.js.erb
$('#<%= @player.id %>').replaceWith('<%= j render 'shared/player_form', player: @player %>');
$('#newPlayer').addClass('disabled');
$('.editPlayer').addClass('disabled');

app/views/players/index.html.erb
<div class="playersTable">
  <div class="playersThead">
    <div class="row">
      <div class="col-3">Name</div>
      <div class="col-3">Email</div>
      <div class="col-3">Wallet</div>
    </div>
  </div>
  <div id="playersTbody">
    <%= render @players %>
  </div>
</div>
<%= link_to 'New player', new_player_path, id: 'newPlayer', class: 'btn btn-primary btn-sm', data: { remote: true } %>

app/views/players/new.js.erb
$('#playersTbody').append('<%= j render 'shared/player_form', player: @player %>');
$('#newPlayer').addClass('disabled');
$('.editPlayer').addClass('disabled');

app/views/players/update.js.erb
$('#newPlayerForm').replaceWith('<%= j render @player %>');
$('#newPlayer').removeClass('disabled');
$('.editPlayer').removeClass('disabled');

app/views/shared/_player_form.html.erb
<div id="newPlayerForm">
  <%= form_with(model: player) do |f| %>
    <div class="row">
      <div class="col-3"><%= f.text_field :name, autofocus: true %></div>
      <div class="col-3"><%= f.email_field :email %></div>
      <div class="col-3"><%= f.number_field :wallet %></div>
      <div class="col-3"><%= f.submit 'Save', class: 'btn btn-primary btn-sm' %></div>
    </div>
  </div>
<% end %>